### ISSUE TITLE
go:  When will the loader new version be updated?

### ISSUE THREAD

**Issue by wuboui** [tableauio/loader#43]
the loader tag hasn't been updated since 2022

**Comment by wenchy** [comment]
New versions just released:
- [protoc-gen-go-tableau-loader v0.3.0](https://github.com/tableauio/loader/releases/tag/cmd%2Fprotoc-gen-go-tableau-loader%2Fv0.3.0)
- [protoc-gen-cpp-tableau-loader v0.5.0](https://github.com/tableauio/loader/releases/tag/cmd%2Fprotoc-gen-cpp-tableau-loader%2Fv0.5.0)
