### ISSUE TITLE
cpp: add hooks before hub switch

### ISSUE THREAD

**Issue by wenchy** [tableauio/loader#8]
old hub -> load -> **ProcessAfterLoad** -> switch (L176) -> new hub 

https://github.com/tableauio/loader/blob/e02236d9c2004310c88ab584eac8644c44aad0a5/_lab/cpp/src/demo/hub.pc.cc#L170-L178

1. Add another messager-level hook `ProcessAfterLoadAll` which is called by  hub-level hook `PostProcess`
2. Add hub-level hook `ProcessAfterLoad` before switch (L176), this hook is for:
   - custom check
   - custom configuration aggregation
   - ...

**Comment by piratf** [comment]
https://github.com/tableauio/loader/blob/e02236d9c2004310c88ab584eac8644c44aad0a5/cmd/protoc-gen-cpp-tableau-loader/embed/hub.pc.h#L74

I hope there will be a call back function on Messager like this. So we can split each function in there own class.
At first I wanted to delay the `ProcessAfterReload` until all the messager had loaded, but if there is a new function to handle this will also be fine.
